name: jsaction
description: A sample JavaScript action to be triggered
runs:
  using: 'node16'
  pre: 'setup.js'
  pre-if: runner.os == 'linux'
  main: 'main.js'
  post: 'cleanup.js'
  post-if: runner.os == 'linux'
branding:
  icon: 'award'
  color: 'green'
