name: module-one-workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  pushtomain:
    runs-on: linux
    steps:
      - name: Run JSACTION
        uses: ./.github/workflows
