name: module-one-workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  pushtomain:
    runs-on: ubuntu-latest
    steps:
      - name: JSACTION
        uses: ./.github/workflows
