name: module-one-scheduler-workflow
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  schedulertomain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JSACTION
        uses: ./.github/workflows/actions
